sudo: false

language: python

python:
  - 3.5
  - 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5.4; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.4" CC="gcc-5.4"; fi
  - pip install -q numpy setuptools
  - python -V

install:
  - pip install .

script:
  - mkdir empty
  - cd empty
  - python -c "import sys;import numexpr3;sys.exit(0 if numexpr3.test().wasSuccessful() else 1)"

# So very tempting to abuse the travis email system...
notifications:
  email: false


