# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: bionic

jobs:
  include:
    # ARMv8 Python 3.6 build
    # - services: docker
    #   arch: arm64
    #   python: 3.6
    #   env: 
    #     - CIBW_BUILD="cp36-*"
    #     - CIBW_BEFORE_BUILD="pip install setuptools numpy"
    #     - CIBW_TEST_COMMAND="python -c 'import sys, numexpr; sys.exit(0 if numexpr.test().wasSuccessful() else 1)'"
    # # ARMv8 Python 3.7 build
    # - services: docker
    #   arch: arm64
    #   python: 3.7
    #   env:
    #     - CIBW_BUILD: "cp37-*"
    # # ARMv8 Python 3.8 build
    # - services: docker
    #   arch: arm64
    #   python: 3.8
    #   env: 
    #     - CIBW_BUILD: "cp38-*"
    # # ARMv8 Python 3.9 build
    # - services: docker
    #   arch: arm64
    #   env: 
    #     - CIBW_BUILD: "cp39-*"
    # PPC64LE Python 3.6 build
    - services: docker
      arch: ppc64le
      python: 3.6
      env:
        - CIBW_BUILD="cp36-*"
        - CIBW_BEFORE_BUILD="pip install setuptools numpy==1.13.3"
        - CIBW_TEST_COMMAND="python -c 'import sys, numexpr; sys.exit(0 if numexpr.test().wasSuccessful() else 1)'"
    # # PPC64LE Python 3.7 build
    # - services: docker
    #   arch: ppc64le
    #   python: 3.7
    #   env:
    #     - CIBW_BUILD: "cp37-*"
    # # PPC64LE Python 3.8 build
    # - services: docker
    #   arch: ppc64le
    #   python: 3.8
    #   env: 
    #     - CIBW_BUILD: "cp38-*"
    # # PPC64LE Python 3.9 build
    # - services: docker
    #   arch: ppc64le
    #   env: 
    #     - CIBW_BUILD: "cp39-*"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - which python
  - which pip
  - python -V

install:
  - pip install cibuildwheel

# addons:
#   artifacts:
#     working_dir: wheelhouse

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse/
